query {
  reviews(pagination: { limit: 10 }) {
    data {
      id
      attributes {
        author
        description
        image {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
