query {
  activities {
    data {
      id
      attributes {
        title
        description
        price
        banner {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
