query {
  slides(pagination: { limit: 100 }) {
    data {
      id
      attributes {
        title
        description
        type
        image {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
