query {
  cities {
    data {
      id
      attributes {
        title
        description
        image {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
