query {
  cities(pagination: { limit: 20 }) {
    data {
      id
      attributes {
        title
        description
        extraInfos
        image {
          data {
            attributes {
              url
            }
          }
        }
        images(pagination: { limit: 6 }) {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
