query {
  privateTrips(pagination: { limit: 500 }) {
    data {
      id
      attributes {
        title
        description
        price
        banner {
          data {
            attributes {
              url
              formats
            }
          }
        }
      }
    }
  }
}
